# Generated by Django 2.1.3 on 2018-12-05 18:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tiposCocinas', models.CharField(choices=[('italiana', 'italiana'), ('vegetariana', 'vegetariana'), ('Española', 'Española')], default='Española', max_length=100)),
                ('alergenos', models.CharField(default='Española', max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
